"""Add gamification tables

Revision ID: 3f8ef46fad30
Revises: aad864ea483a
Create Date: 2025-11-16 03:05:53.063103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8ef46fad30'
down_revision = 'aad864ea483a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('achievement_type', sa.Enum('STREAK', 'LEVEL', 'TRANSACTIONS', 'XP', 'HEART', 'CUSTOM', name='achievementtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('unlock_conditions', sa.Text(), nullable=False),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_achievements_achievement_type'), 'achievements', ['achievement_type'], unique=False)
    op.create_index(op.f('ix_achievements_id'), 'achievements', ['id'], unique=False)
    op.create_table('daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quest_type', sa.Enum('RECORD_EXPENSE', 'RECORD_INCOME', 'REVIEW_TRANSACTIONS', 'CHECK_BALANCE', 'SAVE_MONEY', 'CUSTOM', name='questtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_quests_id'), 'daily_quests', ['id'], unique=False)
    op.create_index(op.f('ix_daily_quests_quest_type'), 'daily_quests', ['quest_type'], unique=False)
    op.create_table('user_gamification_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('streak_days', sa.Integer(), nullable=False),
    sa.Column('last_entry_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('heart_level', sa.Integer(), nullable=False),
    sa.Column('total_xp_earned', sa.Integer(), nullable=False),
    sa.Column('total_quests_completed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gamification_profiles_id'), 'user_gamification_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_user_gamification_profiles_user_id'), 'user_gamification_profiles', ['user_id'], unique=True)
    op.create_table('user_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('achievement_id', sa.Integer(), nullable=False),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['achievement_id'], ['achievements.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['user_gamification_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_achievements_achievement_id'), 'user_achievements', ['achievement_id'], unique=False)
    op.create_index(op.f('ix_user_achievements_id'), 'user_achievements', ['id'], unique=False)
    op.create_index(op.f('ix_user_achievements_profile_id'), 'user_achievements', ['profile_id'], unique=False)
    op.create_table('user_daily_quests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('quest_id', sa.Integer(), nullable=True),
    sa.Column('quest_type', sa.Enum('RECORD_EXPENSE', 'RECORD_INCOME', 'REVIEW_TRANSACTIONS', 'CHECK_BALANCE', 'SAVE_MONEY', 'CUSTOM', name='questtype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('xp_reward', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', name='queststatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('target_value', sa.Integer(), nullable=True),
    sa.Column('quest_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['user_gamification_profiles.id'], ),
    sa.ForeignKeyConstraint(['quest_id'], ['daily_quests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_daily_quests_id'), 'user_daily_quests', ['id'], unique=False)
    op.create_index(op.f('ix_user_daily_quests_profile_id'), 'user_daily_quests', ['profile_id'], unique=False)
    op.create_index(op.f('ix_user_daily_quests_quest_date'), 'user_daily_quests', ['quest_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_daily_quests_quest_date'), table_name='user_daily_quests')
    op.drop_index(op.f('ix_user_daily_quests_profile_id'), table_name='user_daily_quests')
    op.drop_index(op.f('ix_user_daily_quests_id'), table_name='user_daily_quests')
    op.drop_table('user_daily_quests')
    op.drop_index(op.f('ix_user_achievements_profile_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_id'), table_name='user_achievements')
    op.drop_index(op.f('ix_user_achievements_achievement_id'), table_name='user_achievements')
    op.drop_table('user_achievements')
    op.drop_index(op.f('ix_user_gamification_profiles_user_id'), table_name='user_gamification_profiles')
    op.drop_index(op.f('ix_user_gamification_profiles_id'), table_name='user_gamification_profiles')
    op.drop_table('user_gamification_profiles')
    op.drop_index(op.f('ix_daily_quests_quest_type'), table_name='daily_quests')
    op.drop_index(op.f('ix_daily_quests_id'), table_name='daily_quests')
    op.drop_table('daily_quests')
    op.drop_index(op.f('ix_achievements_id'), table_name='achievements')
    op.drop_index(op.f('ix_achievements_achievement_type'), table_name='achievements')
    op.drop_table('achievements')
    # ### end Alembic commands ###

