"""add_daily_reminder_message_id

Revision ID: b60144ef8d38
Revises: 9c8be056d531
Create Date: 2025-01-27 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b60144ef8d38'
down_revision = '9c8be056d531'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_gamification_profiles', sa.Column('daily_reminder_message_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_gamification_profiles', 'daily_reminder_message_id')
    # ### end Alembic commands ###

