"""Add vk_id to users

Revision ID: bd53837546bb
Revises: a920226c4581
Create Date: 2025-11-14 23:14:42.778116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd53837546bb'
down_revision = 'a920226c4581'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_accounts_shared_budget_id', table_name='accounts')
    op.drop_index('idx_accounts_user_active', table_name='accounts', postgresql_where='(is_active = true)')
    op.drop_index('idx_accounts_user_id', table_name='accounts')
    op.drop_index('idx_categories_shared_budget_id', table_name='categories')
    op.drop_index('idx_categories_user_active', table_name='categories', postgresql_where='(is_active = true)')
    op.drop_index('idx_categories_user_id', table_name='categories')
    op.drop_index('idx_goals_status', table_name='goals')
    op.drop_index('idx_goals_user_id', table_name='goals')
    op.drop_index('idx_goals_user_status', table_name='goals', postgresql_where="(status = 'ACTIVE'::goalstatus)")
    op.drop_index('idx_invitations_budget_id', table_name='invitations')
    op.drop_index('idx_invitations_email', table_name='invitations', postgresql_where='(email IS NOT NULL)')
    op.drop_index('idx_invitations_status', table_name='invitations')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_user_unread', table_name='notifications', postgresql_where='(is_read = false)')
    op.drop_index('idx_reports_user_id', table_name='reports')
    op.drop_index('idx_budget_members_budget_id', table_name='shared_budget_members')
    op.drop_index('idx_budget_members_user_budget', table_name='shared_budget_members')
    op.drop_index('idx_tags_user_id', table_name='tags')
    op.drop_index('idx_transactions_account_id', table_name='transactions')
    op.drop_index('idx_transactions_category_id', table_name='transactions')
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_transactions_shared_budget_id', table_name='transactions')
    op.drop_index('idx_transactions_user_date', table_name='transactions')
    op.drop_index('idx_transactions_user_id', table_name='transactions')
    op.add_column('users', sa.Column('vk_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_vk_id'), 'users', ['vk_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_vk_id'), table_name='users')
    op.drop_column('users', 'vk_id')
    op.create_index('idx_transactions_user_id', 'transactions', ['user_id'], unique=False)
    op.create_index('idx_transactions_user_date', 'transactions', ['user_id', sa.text('transaction_date DESC')], unique=False)
    op.create_index('idx_transactions_shared_budget_id', 'transactions', ['shared_budget_id'], unique=False)
    op.create_index('idx_transactions_date', 'transactions', ['transaction_date'], unique=False)
    op.create_index('idx_transactions_category_id', 'transactions', ['category_id'], unique=False)
    op.create_index('idx_transactions_account_id', 'transactions', ['account_id'], unique=False)
    op.create_index('idx_tags_user_id', 'tags', ['user_id'], unique=False)
    op.create_index('idx_budget_members_user_budget', 'shared_budget_members', ['user_id', 'shared_budget_id'], unique=False)
    op.create_index('idx_budget_members_budget_id', 'shared_budget_members', ['shared_budget_id'], unique=False)
    op.create_index('idx_reports_user_id', 'reports', ['user_id'], unique=False)
    op.create_index('idx_notifications_user_unread', 'notifications', ['user_id', 'is_read'], unique=False, postgresql_where='(is_read = false)')
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_index('idx_invitations_status', 'invitations', ['status'], unique=False)
    op.create_index('idx_invitations_email', 'invitations', ['email'], unique=False, postgresql_where='(email IS NOT NULL)')
    op.create_index('idx_invitations_budget_id', 'invitations', ['shared_budget_id'], unique=False)
    op.create_index('idx_goals_user_status', 'goals', ['user_id', 'status'], unique=False, postgresql_where="(status = 'ACTIVE'::goalstatus)")
    op.create_index('idx_goals_user_id', 'goals', ['user_id'], unique=False)
    op.create_index('idx_goals_status', 'goals', ['status'], unique=False)
    op.create_index('idx_categories_user_id', 'categories', ['user_id'], unique=False)
    op.create_index('idx_categories_user_active', 'categories', ['user_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_categories_shared_budget_id', 'categories', ['shared_budget_id'], unique=False)
    op.create_index('idx_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_index('idx_accounts_user_active', 'accounts', ['user_id', 'is_active'], unique=False, postgresql_where='(is_active = true)')
    op.create_index('idx_accounts_shared_budget_id', 'accounts', ['shared_budget_id'], unique=False)
    # ### end Alembic commands ###

